version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:   #replace these
      - SECRET_KEY=234nkdjhfkj2h3k4jhkjshdfkjhkajsdhfkj 
      - DEBUG=1
      - DB_HOST=host
      - DB_NAME=dev
      - DB_USER=YOUR_USER
      - DB_PASS=YOUR_PASS
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=YOUR_USER
      - POSTGRES_PASSWORD=YOUR_PASS